### ISSUE TITLE
Trouble building project in Windows Environment

### ISSUE THREAD

**Issue by Ammar360** [wxllow/applemusicrp#41]
Hi There! 

Love your project! I was trying to see if I could add some features as well, so I downloaded the source code to alter it in Visual Studio. However, everytime I run the command you provided for Windows, I run into the same issue over and over:

PS C:\Users\ammar\Downloads\AMRPD_1.01\applemusicrichpresencefordiscord-master> poetry run python setup_win.py py2exe
running py2exe
running build_py
package init file 'src\applemusicrp\assets\__init__.py' not found (or not a regular file)
package init file 'src\applemusicrp\scripts\__init__.py' not found (or not a regular file)
Analyzing the code
Found 624 modules, 46 are missing, 0 may be missing

  46 missing Modules
  ------------------
? OpenSSL.SSL                         imported from urllib3.contrib.pyopenssl
? OpenSSL.crypto                      imported from urllib3.contrib.pyopenssl
? PIL                                 imported from src.applemusicrp.applemusicrp
? Queue                               imported from urllib3.util.queue
? StringIO                            imported from urllib3.packages.six
? __main__                            imported from bdb, pdb
? _frozen_importlib                   imported from importlib, importlib.abc, zipimport
? _frozen_importlib_external          imported from importlib, importlib._bootstrap, importlib.abc, zipimport
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? _winreg                             imported from appdirs, platform
? assets.FREQUENCIES                  imported from charset_normalizer.cd, charset_normalizer.constant
? asyncio.DefaultEventLoopPolicy      imported from -
? brotli                              imported from urllib3.response, urllib3.util.request
? brotlicffi                          imported from urllib3.response, urllib3.util.request
? collections.Mapping                 imported from urllib3._collections
? collections.MutableMapping          imported from urllib3._collections
? com.sun                             imported from appdirs
? com.sun.jna                         imported from appdirs
? com.sun.jna.platform                imported from appdirs
? cryptography                        imported from requests, urllib3.contrib.pyopenssl
? cryptography.hazmat.backends.openssl imported from urllib3.contrib.pyopenssl
? cryptography.x509                   imported from urllib3.contrib.pyopenssl
? cryptography.x509.extensions        imported from urllib3.contrib.pyopenssl
? dummy.Process                       imported from multiprocessing.pool
? dummy_threading                     imported from requests.cookies
? java.lang                           imported from platform
? numpy                               imported from toml.encoder
? org.python.core                     imported from copy, pickle
? os.path                             imported from ctypes._aix, distutils.file_util, os, pkgutil, py_compile, requests.adapters, src.applemusicrp.utils, sysconfig, toml.decoder, tracemalloc, unittest, unittest.util
? packages.six.moves                  imported from urllib3.connectionpool, urllib3.util.queue, urllib3.util.response
? packages.six.moves.http_client      imported from urllib3.connection, urllib3.exceptions
? packages.six.moves.urllib.parse     imported from urllib3.poolmanager, urllib3.request
? pep517                              imported from importlib.metadata
? pystray                             imported from src.applemusicrp.applemusicrp
? pythoncom                           imported from src.applemusicrp.rpc
? readline                            imported from cmd, code, pdb
? resource                            imported from test.support
? rumps                               imported from src.applemusicrp.applemusicrp
? simplejson                          imported from requests.compat
? socks                               imported from urllib3.contrib.socks
? urllib3_secure_extra                imported from urllib3
? util.SKIPPABLE_HEADERS              imported from urllib3.connection
? util.SKIP_HEADER                    imported from urllib3.connection
? win32api                            imported from appdirs
? win32com.client                     imported from src.applemusicrp.rpc
? win32com.shell                      imported from appdirs
Building 'dist/windows/AppleMusicRP.exe'.
Traceback (most recent call last):
  File "C:\Users\ammar\Downloads\AMRPD_1.01\applemusicrichpresencefordiscord-master\setup_win.py", line 53, in <module>
    setup(
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
    return run_commands(dist)
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
    dist.run_commands()
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\dist.py", line 1229, in run_command
    super().run_command(command)
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\py2exe\distutils_buildexe.py", line 204, in run
    self._run()
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\py2exe\distutils_buildexe.py", line 285, in _run
    builder.build()
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\py2exe\runtime.py", line 245, in build
    self.build_exe(target, exe_path, options.libname)
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\py2exe\runtime.py", line 364, in build_exe
    if self.options.version_info:
    
    Are there some libraries missing in the pyproject.toml file you provided? I have run the install py2exe command several times, and it states that there is nothing else to add, yet I get this error. I know you're busy, but if you could help me build this I'd love to help you fix some of the bugs/issues and will open up pull requests with some edits soon!
    
    Thanks!

**Comment by wxllow** [comment]
Hey, could you please give the ending part of the error?

**Comment by Ammar360** [comment]
Oh my apologies, here's the whole thing:

PS C:\Users\ammar\Downloads\AMRPD_1.01\applemusicrichpresencefordiscord-master> poetry run python setup_win.py py2exe
running py2exe
running build_py
package init file 'src\applemusicrp\assets\__init__.py' not found (or not a regular file)
package init file 'src\applemusicrp\scripts\__init__.py' not found (or not a regular file)
Analyzing the code
Found 624 modules, 46 are missing, 0 may be missing

  46 missing Modules
  ------------------
? OpenSSL.SSL                         imported from urllib3.contrib.pyopenssl
? OpenSSL.crypto                      imported from urllib3.contrib.pyopenssl
? PIL                                 imported from src.applemusicrp.applemusicrp
? Queue                               imported from urllib3.util.queue
? StringIO                            imported from urllib3.packages.six
? __main__                            imported from bdb, pdb
? _frozen_importlib                   imported from importlib, importlib.abc, zipimport
? _frozen_importlib_external          imported from importlib, importlib._bootstrap, importlib.abc, zipimport      
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? _winreg                             imported from appdirs, platform
? assets.FREQUENCIES                  imported from charset_normalizer.cd, charset_normalizer.constant
? asyncio.DefaultEventLoopPolicy      imported from -
? brotli                              imported from urllib3.response, urllib3.util.request
? brotlicffi                          imported from urllib3.response, urllib3.util.request
? collections.Mapping                 imported from urllib3._collections
? collections.MutableMapping          imported from urllib3._collections
? com.sun                             imported from appdirs
? com.sun.jna                         imported from appdirs
? com.sun.jna.platform                imported from appdirs
? cryptography                        imported from requests, urllib3.contrib.pyopenssl
? cryptography.hazmat.backends.openssl imported from urllib3.contrib.pyopenssl
? cryptography.x509                   imported from urllib3.contrib.pyopenssl
? cryptography.x509.extensions        imported from urllib3.contrib.pyopenssl
? dummy.Process                       imported from multiprocessing.pool
? dummy_threading                     imported from requests.cookies
? java.lang                           imported from platform
? numpy                               imported from toml.encoder
? org.python.core                     imported from copy, pickle
? os.path                             imported from ctypes._aix, distutils.file_util, os, pkgutil, py_compile, requests.adapters, src.applemusicrp.utils, sysconfig, toml.decoder, tracemalloc, unittest, unittest.util
? packages.six.moves                  imported from urllib3.connectionpool, urllib3.util.queue, urllib3.util.response
? packages.six.moves.http_client      imported from urllib3.connection, urllib3.exceptions
? packages.six.moves.urllib.parse     imported from urllib3.poolmanager, urllib3.request
? pep517                              imported from importlib.metadata
? pystray                             imported from src.applemusicrp.applemusicrp
? pythoncom                           imported from src.applemusicrp.rpc
? readline                            imported from cmd, code, pdb
? resource                            imported from test.support
? rumps                               imported from src.applemusicrp.applemusicrp
? simplejson                          imported from requests.compat
? socks                               imported from urllib3.contrib.socks
? urllib3_secure_extra                imported from urllib3
? util.SKIPPABLE_HEADERS              imported from urllib3.connection
? util.SKIP_HEADER                    imported from urllib3.connection
? win32api                            imported from appdirs
? win32com.client                     imported from src.applemusicrp.rpc
? win32com.shell                      imported from appdirs
Building 'dist/windows/AppleMusicRP.exe'.
Traceback (most recent call last):
  File "C:\Users\ammar\Downloads\AMRPD_1.01\applemusicrichpresencefordiscord-master\setup_win.py", line 53, in <module>
    setup(
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
    return run_commands(dist)
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
    dist.run_commands()
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\dist.py", line 1229, in run_command
    super().run_command(command)
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\py2exe\distutils_buildexe.py", line 204, in run
    self._run()
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\py2exe\distutils_buildexe.py", line 285, in _run
    builder.build()
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\py2exe\runtime.py", line 245, in build
    self.build_exe(target, exe_path, options.libname)
  File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\py2exe\runtime.py", line 364, in build_exe
    if self.options.version_info:
AttributeError: 'Namespace' object has no attribute 'version_info'

**Comment by Ammar360** [comment]
> Hey, could you please give the ending part of the error?

Oh my apologies, here's the whole thing:

PS C:\Users\ammar\Downloads\AMRPD_1.01\applemusicrichpresencefordiscord-master> poetry run python setup_win.py py2exe
running py2exe
running build_py
package init file 'src\applemusicrp\assets_init_.py' not found (or not a regular file)
package init file 'src\applemusicrp\scripts_init_.py' not found (or not a regular file)
Analyzing the code
Found 624 modules, 46 are missing, 0 may be missing

46 missing Modules
? OpenSSL.SSL imported from urllib3.contrib.pyopenssl
? OpenSSL.crypto imported from urllib3.contrib.pyopenssl
? PIL imported from src.applemusicrp.applemusicrp
? Queue imported from urllib3.util.queue
? StringIO imported from urllib3.packages.six
? main imported from bdb, pdb
? _frozen_importlib imported from importlib, importlib.abc, zipimport
? _frozen_importlib_external imported from importlib, importlib._bootstrap, importlib.abc, zipimport
? _posixshmem imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? _winreg imported from appdirs, platform
? assets.FREQUENCIES imported from charset_normalizer.cd, charset_normalizer.constant
? asyncio.DefaultEventLoopPolicy imported from -
? brotli imported from urllib3.response, urllib3.util.request
? brotlicffi imported from urllib3.response, urllib3.util.request
? collections.Mapping imported from urllib3._collections
? collections.MutableMapping imported from urllib3._collections
? com.sun imported from appdirs
? com.sun.jna imported from appdirs
? com.sun.jna.platform imported from appdirs
? cryptography imported from requests, urllib3.contrib.pyopenssl
? cryptography.hazmat.backends.openssl imported from urllib3.contrib.pyopenssl
? cryptography.x509 imported from urllib3.contrib.pyopenssl
? cryptography.x509.extensions imported from urllib3.contrib.pyopenssl
? dummy.Process imported from multiprocessing.pool
? dummy_threading imported from requests.cookies
? java.lang imported from platform
? numpy imported from toml.encoder
? org.python.core imported from copy, pickle
? os.path imported from ctypes.aix, distutils.file_util, os, pkgutil, py_compile, requests.adapters, src.applemusicrp.utils, sysconfig, toml.decoder, tracemalloc, unittest, unittest.util
? packages.six.moves imported from urllib3.connectionpool, urllib3.util.queue, urllib3.util.response
? packages.six.moves.http_client imported from urllib3.connection, urllib3.exceptions
? packages.six.moves.urllib.parse imported from urllib3.poolmanager, urllib3.request
? pep517 imported from importlib.metadata
? pystray imported from src.applemusicrp.applemusicrp
? pythoncom imported from src.applemusicrp.rpc
? readline imported from cmd, code, pdb
? resource imported from test.support
? rumps imported from src.applemusicrp.applemusicrp
? simplejson imported from requests.compat
? socks imported from urllib3.contrib.socks
? urllib3_secure_extra imported from urllib3
? util.SKIPPABLE_HEADERS imported from urllib3.connection
? util.SKIP_HEADER imported from urllib3.connection
? win32api imported from appdirs
? win32com.client imported from src.applemusicrp.rpc
? win32com.shell imported from appdirs
Building 'dist/windows/AppleMusicRP.exe'.
Traceback (most recent call last):
File "C:\Users\ammar\Downloads\AMRPD_1.01\applemusicrichpresencefordiscord-master\setup_win.py", line 53, in
setup(
File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools_init.py", line 87, in setup
return distutils.core.setup(**attrs)
File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools_distutils\core.py", line 177, in setup
return run_commands(dist)
File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools_distutils\core.py", line 193, in run_commands
dist.run_commands()
File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools_distutils\dist.py", line 968, in run_commands
self.run_command(cmd)
File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools\dist.py", line 1229, in run_command
super().run_command(command)
File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\setuptools_distutils\dist.py", line 987, in run_command
cmd_obj.run()
File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\py2exe\distutils_buildexe.py", line 204, in run
self._run()
File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\py2exe\distutils_buildexe.py", line 285, in _run
builder.build()
File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\py2exe\runtime.py", line 245, in build
self.build_exe(target, exe_path, options.libname)
File "C:\Users\ammar\AppData\Local\pypoetry\Cache\virtualenvs\applemusicrp-9nq2FRJt-py3.9\lib\site-packages\py2exe\runtime.py", line 364, in build_exe
if self.options.version_info:
AttributeError: 'Namespace' object has no attribute 'version_info'

**Comment by Ammar360** [comment]
@wxllow just checking in on this

**Comment by wxllow** [comment]
Unfortunately I cannot figure out ur problem, which version of Python are u using and where did you download Python from?

**Comment by Ammar360** [comment]
I'm using VisualStudio as a compiler, and I have both the Windows and Linux versions of Python installed

**Comment by wxllow** [comment]
> I'm using VisualStudio as a compiler, and I have both the Windows and Linux versions of Python installed

I'm not familiar with VisualStudio... why don't you use the command line instructions from the README?
